name: ESP32 Camera Examples

on:
  push:
  pull_request:

env:
  SKETCHES: |
    examples/Camera/motion-capture
    examples/Camera/snapshot-camera
    examples/Camera/mjpeg-camera
    examples/Camera/rtsp-camera

jobs:
  compile-camera-examples:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: "esp32:esp32:esp32"
            platform-url: "https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyserial

      - name: Compile ESP32 camera examples
        uses: arduino/compile-sketches@v1
        with:
          fqbn: ${{ matrix.board }}
          platforms: |
            - name: esp32:esp32
              source-url: ${{ matrix.platform-url }}
          libraries: |
            - source-path: ./
            - source-url: https://github.com/Links2004/arduinoWebSockets.git
            - source-url: https://github.com/bblanchon/ArduinoJson.git
          sketch-paths: ${{ env.SKETCHES }}
          cli-compile-flags: |
            - --warnings=none